apiVersion: v1
kind: Service
metadata:
  name: inventory-service
spec:
  selector:
    app: inventory
  ports:
    - protocol: TCP
      port: 8084          # Cluster-wide port (can stay as 8084)
      targetPort: 8084    # Port inside the container
      nodePort: 30084     # Exposed port on the Minikube host machine (30000-32767 range)
  type: NodePort
